[2022-05-08 09:15:03,606] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag_v3.third_task manual__2022-05-08T09:15:01.856115+00:00 [queued]>
[2022-05-08 09:15:03,632] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag_v3.third_task manual__2022-05-08T09:15:01.856115+00:00 [queued]>
[2022-05-08 09:15:03,634] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-08 09:15:03,636] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2022-05-08 09:15:03,637] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-08 09:15:03,678] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): third_task> on 2022-05-08 09:15:01.856115+00:00
[2022-05-08 09:15:03,685] {standard_task_runner.py:52} INFO - Started process 474 to run task
[2022-05-08 09:15:03,704] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'first_dag_v3', 'third_task', 'manual__2022-05-08T09:15:01.856115+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpbtlzv8hs', '--error-file', '/tmp/tmpvs_bs_ff']
[2022-05-08 09:15:03,709] {standard_task_runner.py:80} INFO - Job 7: Subtask third_task
[2022-05-08 09:15:03,852] {task_command.py:369} INFO - Running <TaskInstance: first_dag_v3.third_task manual__2022-05-08T09:15:01.856115+00:00 [running]> on host ef82a602b7b6
[2022-05-08 09:15:04,235] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=faceit
AIRFLOW_CTX_DAG_ID=first_dag_v3
AIRFLOW_CTX_TASK_ID=third_task
AIRFLOW_CTX_EXECUTION_DATE=2022-05-08T09:15:01.856115+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-08T09:15:01.856115+00:00
[2022-05-08 09:15:04,237] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-08 09:15:04,241] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hello world task -3!']
[2022-05-08 09:15:04,280] {subprocess.py:85} INFO - Output:
[2022-05-08 09:15:04,288] {subprocess.py:92} INFO - hello world task -3!
[2022-05-08 09:15:04,295] {subprocess.py:96} INFO - Command exited with return code 0
[2022-05-08 09:15:04,446] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=first_dag_v3, task_id=third_task, execution_date=20220508T091501, start_date=20220508T091503, end_date=20220508T091504
[2022-05-08 09:15:04,563] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-05-08 09:15:04,661] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
