[2022-05-08 09:16:54,850] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag_v4.third_task manual__2022-05-08T09:16:52.490876+00:00 [queued]>
[2022-05-08 09:16:54,874] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag_v4.third_task manual__2022-05-08T09:16:52.490876+00:00 [queued]>
[2022-05-08 09:16:54,875] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-08 09:16:54,876] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2022-05-08 09:16:54,877] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-08 09:16:54,913] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): third_task> on 2022-05-08 09:16:52.490876+00:00
[2022-05-08 09:16:54,920] {standard_task_runner.py:52} INFO - Started process 508 to run task
[2022-05-08 09:16:54,930] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'first_dag_v4', 'third_task', 'manual__2022-05-08T09:16:52.490876+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmphf7ei45t', '--error-file', '/tmp/tmpa96z6j0t']
[2022-05-08 09:16:54,942] {standard_task_runner.py:80} INFO - Job 10: Subtask third_task
[2022-05-08 09:16:55,109] {task_command.py:369} INFO - Running <TaskInstance: first_dag_v4.third_task manual__2022-05-08T09:16:52.490876+00:00 [running]> on host ef82a602b7b6
[2022-05-08 09:16:55,401] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=faceit
AIRFLOW_CTX_DAG_ID=first_dag_v4
AIRFLOW_CTX_TASK_ID=third_task
AIRFLOW_CTX_EXECUTION_DATE=2022-05-08T09:16:52.490876+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-08T09:16:52.490876+00:00
[2022-05-08 09:16:55,410] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-08 09:16:55,418] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hello world task -3!']
[2022-05-08 09:16:55,440] {subprocess.py:85} INFO - Output:
[2022-05-08 09:16:55,461] {subprocess.py:92} INFO - hello world task -3!
[2022-05-08 09:16:55,474] {subprocess.py:96} INFO - Command exited with return code 0
[2022-05-08 09:16:55,570] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=first_dag_v4, task_id=third_task, execution_date=20220508T091652, start_date=20220508T091654, end_date=20220508T091655
[2022-05-08 09:16:55,667] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-05-08 09:16:55,856] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
