[2022-05-08 09:12:45,307] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag_v2.third_task manual__2022-05-08T09:12:42.283597+00:00 [queued]>
[2022-05-08 09:12:45,324] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag_v2.third_task manual__2022-05-08T09:12:42.283597+00:00 [queued]>
[2022-05-08 09:12:45,326] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-08 09:12:45,327] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2022-05-08 09:12:45,329] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-08 09:12:45,385] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): third_task> on 2022-05-08 09:12:42.283597+00:00
[2022-05-08 09:12:45,397] {standard_task_runner.py:52} INFO - Started process 445 to run task
[2022-05-08 09:12:45,432] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'first_dag_v2', 'third_task', 'manual__2022-05-08T09:12:42.283597+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp5g1x9f_r', '--error-file', '/tmp/tmp2qw3fsiv']
[2022-05-08 09:12:45,435] {standard_task_runner.py:80} INFO - Job 5: Subtask third_task
[2022-05-08 09:12:45,957] {task_command.py:369} INFO - Running <TaskInstance: first_dag_v2.third_task manual__2022-05-08T09:12:42.283597+00:00 [running]> on host ef82a602b7b6
[2022-05-08 09:12:46,221] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=faceit
AIRFLOW_CTX_DAG_ID=first_dag_v2
AIRFLOW_CTX_TASK_ID=third_task
AIRFLOW_CTX_EXECUTION_DATE=2022-05-08T09:12:42.283597+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-08T09:12:42.283597+00:00
[2022-05-08 09:12:46,223] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-08 09:12:46,225] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hello world task -3!']
[2022-05-08 09:12:46,280] {subprocess.py:85} INFO - Output:
[2022-05-08 09:12:46,296] {subprocess.py:92} INFO - hello world task -3!
[2022-05-08 09:12:46,304] {subprocess.py:96} INFO - Command exited with return code 0
[2022-05-08 09:12:46,438] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=first_dag_v2, task_id=third_task, execution_date=20220508T091242, start_date=20220508T091245, end_date=20220508T091246
[2022-05-08 09:12:46,495] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-05-08 09:12:46,651] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
